@echo off
echo Starting Spotify Stats Application...
echo.
echo Starting Flask backend...
start cmd /k "cd react-spotify && python app.py"
echo.
echo Starting React frontend...
start cmd /k "cd react-spotify\client && npm start"
echo.
echo Both servers are starting. Please wait a moment...
echo Backend: http://localhost:5000
echo Frontend: http://localhost:3000 